osx_image: xcode10.2  
language: swift

script:
- xcodebuild -scheme AudioRecorder -workspace AudioRecorder.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.2'  build test

after_success:
  - bash <(curl -s https://codecov.io/bash)
