osx_image: xcode10.2  
language: swift

script:
  - xcodebuild test -scheme AudioRecorder-iOS -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 8" | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash)
